### ISSUE TITLE
Valet not working with WiFi adapter

### ISSUE THREAD

**Issue by raymondtri** [cretueusebiu/valet-windows#120]
Over ethernet works just fine, but the moment we try to run valet with the Acrylic DNS configured on a wifi adapter, it doesn't even hit valet.

**Comment by Webinsane** [comment]
I have same issue. Not sure if this is even possible through WiFi. I have read gazillion tutorials and none mentions the WiFi configuration.

**Comment by naczu** [comment]
I think it is dead project

**Comment by Pragalbha-Patil** [comment]
Okay so I fixed the issue on my machine, Open Network and sharing center and open Wi-Fi Properties, Double click on IPv4 and configure your DNS server address manually,
The Preferred DNS Server : 127.0.0.1
The Alternate DNS Server : 192.168.0.1 // since this is my router gateway address. Configure it to your router gateway.
You can also refer the screenshot below to refer the same.
![image](https://user-images.githubusercontent.com/44872076/75022030-5f237c00-54bb-11ea-9fe8-8f4a8dbfb823.png)
