### ISSUE TITLE
Serving sites with "valet park" not working

### ISSUE THREAD

**Issue by Almusamim** [cretueusebiu/valet-windows#82]
When I run valet park I get this "_This directory has been added to Valet's paths._"
I have directories in the folder, but no sites are being registered.

When I run valet links it is empty.

I can only get it to work with valet link.

I have the latest version installed.

**Comment by cretueusebiu** [comment]
Have you tried running the terminal as Administrator ?

**Comment by Almusamim** [comment]
@cretueusebiu yes I'm using PowerShell as administrator

**Comment by cretueusebiu** [comment]
I can't reproduce this on my end. 
What version of Windows do you have ? Where

**Comment by Almusamim** [comment]
no, they are on the same C drive.
I have created a directory in my user then ran valet park

**Comment by twd3** [comment]
OPEN POWERSHELL AS ADMIN AND:
composer global require cretueusebiu/valet-windows
THEN:
valet install
THEN:
valet start

Don't forget to: Take care of local DNS: Go to adaptor IP4 and set preferred DNS to: 127.0.0.1 and then IP6 and set perf to:  ::1

Just fought it and figured it out...

**Comment by schnetzi** [comment]
I was having this problem now for a while and found a solution for myself. I built up on @twd3 s comment. Thanks for that.

Steps:
* open powershell as admin
* run `valet uninstall` (if installed)
* In `C:\Users\[Username]\` I had two folders. One called `.valet` and one called `.config`
  * **delete** both folders (check in `.config` if it is only for valet. Otherwise just delete the valet settings)
* run `composer global require cretueusebiu/valet-windows`
* run `valet install`
* run `valet start`
* change DNS-settings (IPv4 to `127.0.0.1` and IPv6 to `::1`)
* run `ipconfig /flushdns`

Hope it helps someone.

**Comment by zinououchikh** [comment]
schnetzi thank you broo, i resolved my issue due to ur comment

**Comment by Jagdish-J-P** [comment]
@schnetzi Thanks bro. Your solution worked like charm.
